### ISSUE TITLE
Crash immediately

### ISSUE THREAD

**Issue by Danlar15** [slasktrat/com.verisure.yale.doorman#1]
I truly waited for this app so I'm grateful that your developing it!

Unfortunately the app crashes immediately and I don't even have any chance to type my credentials.

**Comment by slasktrat** [comment]
Hi. My mistake :( I did not realize that Athom expected the node_modules to be checked in. I have fixed now, but it takes 2-3 days to get new version approved. I can add you to the alpha list if you want to test it, or you can install the app with athom-cli.

**Comment by djeskoswe** [comment]
add me to the alpha please,  niklas@bnehome.se

**Comment by slasktrat** [comment]
Done!

**Comment by djeskoswe** [comment]
installed and running... thanks

**Comment by Danlar15** [comment]
Hi,

add me to the alpha please, daniel@danicia.se <mailto:daniel@danicia.se>

//Daniel

**Comment by slasktrat** [comment]
Hi @Danlar15, you are now in the alpha channel

**Comment by Danlar15** [comment]
Thnx! Stupid question, but where do I find the Alpha channel?

**Comment by slasktrat** [comment]
I'm not 100% sure how it looks for you, but I think you should have a drop down list above the app name in the install page? Then you must select the alpha version and click the install button again.

**Comment by Danlar15** [comment]
Thnx! I found it! Now this text appears: "You are invited for the alpha channel of this app. Click here to switch to this version" but I get the message: "The resource was not found" when I click on the link... :-(

**Comment by sebastianyberg** [comment]
Hi, can u add med på alpha? 
sebastianyberg@gmail.com ? 

//Sebastian

**Comment by slasktrat** [comment]
Done! :)

**Comment by sebastianyberg** [comment]
i only get "The resource was not found" :(

**Comment by slasktrat** [comment]
It seems maybe Athom have some issues with the alpha channels atm. I added you, but when I refreshed the list of alpha participants you where gone. Tried to add you again and the same happened. Tried the third time, and now you seem to stick on the list, maybe it will work now?

**Comment by sebastianyberg** [comment]
dosen't work, I try later on. :) thanks!

**Comment by slasktrat** [comment]
Now the fixed version got approved by athom and is published to the beta channel (version 0.0.3)

**Comment by slasktrat** [comment]
Working version published in beta channel
