### ISSUE TITLE
Is it possible to have an alarm off trigger?

### ISSUE THREAD

**Issue by marcusmaker** [slasktrat/com.verisure.yale.doorman#5]
Hi, great app!
Since we use the autolock in our home, there's a lot of lock/unlock events.
It would be great if it could trigger on "alarm off", i.e. when the first person enters home a flow could start.

**Comment by slasktrat** [comment]
Hi. I will see what I can do :)

**Comment by slasktrat** [comment]
Added new triggers now to detect alarm state changes. Either install via cli (use the beta branch) or send me your email address and I will add you to the alpha channel in athom app store.

**Comment by marcusmaker** [comment]
Wow, great!
Will look into that soon 😊
