### ISSUE TITLE
Support for more than one alarm system

### ISSUE THREAD

**Issue by alydersen** [slasktrat/com.verisure.yale.doorman#6]
First off all - thank you for all your effort.

I have more than one alarm system installed and it seems like your app picks the first one. Is it possible to add a possibility to choose system in the settings?

Andreas

**Comment by slasktrat** [comment]
Hi

I only have one system, so I haven't been able to test with multiple systems. I thought all locks would be listed and available - accross all systems, but I will take another look at it as soon as I got the time. 

If I would need some logs, are you able to assist with that?

**Comment by slasktrat** [comment]
Hello again. As mentioned I only have one system, so I'm debugging in the dark here. But I cannot see any logical reason why you only see one system in the app. I tried to make a tiny change however, so if you pull the latest commit from the "beta" branch now and install via cli. Then check if you get all systems.

**Comment by alydersen** [comment]
I’m on vacation now - will test as soon as I’m home

**Comment by alydersen** [comment]
Seems to work perfect now. Thanks!
