### ISSUE TITLE
Verisure customer?

### ISSUE THREAD

**Issue by mackelito** [slasktrat/com.verisure.yale.doorman#8]
Do I understand this correctly that you need to be a Verisure customer to use this? (sorry for posting a general question in github..)

**Comment by slasktrat** [comment]
Hi. You don't need to be a Verisure customer or have any subscription, but you will need to have the Verisure module.

**Comment by HaBeNi** [comment]
Hi. I have the Verisure module, but are not a customer. How should I Connect to the Yale Doorman unit? The app asks for username & password. which I obviously doesn't have. Thanks in advance. MUCH APPRECIATED!

**Comment by slasktrat** [comment]
Hi. You must register with Verisure to create an account, but you don't need a paid subscription :)

**Comment by HaBeNi** [comment]
Hi again, and thanks! 
Have an account now and are trying to register my Yale Doorman. The registration app on the Norwegian Verisure website insists that I also must register a home central (main unit) to finalize the registration :(

**Comment by HaBeNi** [comment]
Sorry, my fault. I also need the Verisure VBox Micro.

**Comment by slasktrat** [comment]
Yes, that is correct
